---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
    checks:
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false

ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- fonts/
- features/
- "features/bootstrap/FeatureContext.php"
- tests/
- "Strebo/WebSocketServer.php"
- documentation/
- libs/
- resources/
- "composer.lock"
- "config.json"
- "composer.json"
- "README.md"
- "codeclimate.sh"