language: php
php:
- 5.5
- 5.6
- 7.0
- hhvm
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit tests/Test.php

env:
  global:
  - secure: joOZP/EBo/eDWv9hXalXrrS0R9OH/IC19wqtIiEzA3ENj+8p12ijH0M9yHq4NEynNNBXThMbySGq7iBg1dixhcvzn0/BaPRA7+HvKfvyrj1vb0i+/XSVDDlVEk6/227STeIWM/PKmUVUmw10TW2t9RyUliOmvFazDm905kkxPDb/14GquPn7x3XmKdne6AfDjyHLKWN0nucoS2E7r4akDH16dN0sZ1JpXaDa6DhGyGTnRhC/LF1hjW1CD1k4TYlvLcggz0x6egjpJZ3UZIqC9oa78WPZOweRLd8OFPmT3DSA1OJspa/sEsRawUTfCpRN7oxhvzr3lg8buesqr3CDlNxzlSa9FMgVDeU0dA8dUK3vaf3DF+7uWx6XLucNSwHMFWRDkC5mgVoyRHFdpRqbcdNk6iubZb1lT8R1u9RdGonp1LQGCAacoTWPXLhu9J6kd4B+PGJPXJShidjVHwkuKICXriTS9S6mMeaqAiNh9hG+crqvF9h/xdBvEfbrk0yvO+2A23uulyPpzW1QHxo0Uz4jx9qwf8nho2v8zD5JxBTktgh0MaXiNOIg8hX6OOZtEMYc6+x0r8zZfZLTURhI2W5PyZb+ih2XmWnD+MCqjDZkxzKs/f3eKQLGsngKqLKn2UbluxzqxWa0hjuiAvq7TaT/sx99d6l0D+Fny6MaoSs=
  - secure: s2Rr+EcmZsfwKse0xSEaZSRaPO+BClgXRoFk0pD6F17iYc1dlyf7cxKqTEYtdRbx/uZ9BrIoGFiET/x6VMJ70dSoV9UE/LtmYDI9moHWAQgEoLrP3R1Y8TYwwt/AY5bQqhn1khBZG/s2HinJMbYLvtFB5BYQnbc1r3JzBUrDBXIahmf7vl9ZimRzahtVzKClUlCOpdEsJ1SYpnSO66IslLdzo06BHlUPITU+LwoQsJxzaw4Ttgk/HmqcwoDJ9ZswI5OBMXFSd7+SgFRoX5sOnUKaOrB2cMHif37SY2pzJ9iIhrkfQ/F7jndN+lcxY/lZTuWzeH/rLZVTQL65VqeiXFKiLpNhOaCWPw5tAdBjenotIPgcrvlQ5mF6ze8yQgspgxJb6U9tuHt7Kgf8fO4gIxQmal3Q1dICJJ2gSxEZT7HCZg6LT7A4CDTuKqjPHan2txyYzAKPpBSyOxsnFyt/i/LbgoGJQA+nKgIJWtPaJyKkRwhv4FILuQ9POV68rK21jcaV8kJwa0Pf84jo+Qcu5RfjzztPklJwYnpvGK5y80j21kgZYEfuEqwRqtVtgGEV5o5y5Y12/okEF7GYgzm6LGc6w1Tcm83RCJlKG07PGnHpPI12L1i/HaIiRLoUwrwC75PbrAmK/wzd7oeeUepyfom+6FA/HMyQp1b6SgKDVxY=

after_success:
 "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://strebo.net/"