language: php
php:
- 5.4
- 5.5
- hhvm
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit Test.php
<<<<<<< HEAD
deploy:
  api_key:
    secure: cJsdev0LdKesz8dHIvKHTmVcE27alQKOA3Q1VKUovYAvNHZObUEpqU3MUYa5WcaajHCub1Cp+caYOboT7Ox0Iry1Rc0Acn2iAcTrUuONBFiHo3bRILfIbdF5og2Yro99znX+QHumiUb3P0Niznbla5x71sPu8Nf42N+b7nIkjtBr9vDO84legx7PobfBnCxERTmowa5cx8ZGlbit+6LgkB80h+7HNNuSgXQsawQCGNAW50k5jgy7gaYnTbKknt0uklqurq2dkx1FnV30JTq8okvpY143e6Uls41CzRqGLeNPnDnTVGhww94ZiVcBQ5wLWb4NIlO+XsFZ5h/vel0eJfc45Ob38qpIlb7sM/DyaYHDFK6J+Utuea2NMFKQgmqw4fUiZTffFfGBwKQBvz92SP/aPEctNIIrXabCkW4Kw2s8kDbxGXhFz6tSarIgjKWaC4MTfCTwiUr6sKXZ16CyLBBSgANC+Vk+CXUHLcfNLZGbFP++j6dxqdh059464EIJ5eW/Que5bnbiu5h5y3pnTE4XbFZGvLRs5b+T8H9iqn3CIbTQ16Od4oFnZ+8SldOkE1oDIwbCjTVSIn68FWk8DA2JeACUJbRA0CzN2OdHE0kW0k73KTCLcasoMsBZ3HaHgGMJHvVPIrXgqG51qb73L5Et/RIV71lQxiGShFkjQCA=
=======

deploy:
  provider: heroku
  api_key: "YOUR API KEY"
>>>>>>> 56e8b7849f50fab91c9417195ab79c0919282bd1
