language: php
jdk: openjdk7
sudo: false
php:
- 5.6
- 7.0
- hhvm
before_install:
- composer self-update
- composer update
install:
- travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.zip
- unzip -qq sonar-scanner-2.6.zip
- composer install --prefer-dist
before_script:
- echo "sonar.host.url=http://sonarqube.it.dh-karlsruhe.de" >> sonar-scanner-2.6/conf/sonar-scanner.properties
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist Strebo/ tests/
- sonar-scanner-2.6/bin/sonar-scanner
after_script:
- vendor/bin/test-reporter
env:
  global:
  - secure: ipTANwdmPIUBqutBZoVRaVVc2gcqQXlbJ0nmz4pvj7G11zdjWJ1fhLPdjmj/8MTav8rheMDaaxFFHn7DJb5HFCRDD1TccLNxYpu9cp10AaZe52nq8dIMgQHjgXjxq75aCsZWIdIsM4S5fzIg0Vc1fEuEjM3boC77WdRH32w7opnAy1L84PoJeseBphIRe032ENmMMCr3gTiuyKj9SsS0sWCwjxrqxWEtUp9u89rt30dMmFv3DJE2D4sjykFHTuMq1Uxki1QsJhmGZl1ZQpj7PqPV9DnBWsqnQfzf9gEMkXEaVc4fhvsIqIrJgAHvPA8xw954ZsgsYyAVmtvVWUmd7JxhVjm6+imx50D5RKwweB3tb0fI1od1K/GF8U6gjAFIaEIs9SbW8XJucAElfxT8rB6BPs0wzf6NB/KJthRM4DIhLXME7OgbTdsiDK8o/EdQo04c3EryLTt3qdamjWb5UdVtsso0OqjawMI9UHk/Rm9jxu2Iqm6izjRJPWfw45t4HEfiML21044+DCPZKUV7afBT1AmrxgBM/h3wMxmEqqwc6RJt12pUJP+6YLgP0jAcxoIhSTOZwvnHyswIhVH5LLAGv2I64NUEEYAtsOnnQRPrDEK0T4GA3UaZL1JAqZNf3Z7iWfOgnXzYfKvy07kaiZs7vOGekzyNu8IAspFhDL4=
  - secure: xk1vBCpJpmcdIaiqmQ+4A8HXJqGP2tWp8+zAsK13Yqh+3qexfFI4rIp4nd/hzGHuXggGW2YHY76H9LEeCtUbZD0pHOJsJJxnCuIQ3/ArUNFcHhAOxNa+C5sICMXtfIR+w++tw0nvp+pk1P4nivnpZr9RjkdEYAzH1G7/NdMDbhqK+K/Yti0WorrbulmA40p40LjDPuk6nwNpi6OCEjOUaT6g1l3EIMUxTzLKdGU8KFkUeNma3ZME66e/SKiuRefMZJvU6QSVb+ZokYkhYQ5msV/f766JAAZzKxgrVaOiWmAcy5LgwZ63L27VKenI0d924sMAsPoBhIw32KtOT2pGXT1nxs9q97W5o+bL0wLZGW2vqdpPF1YzS4ACTT3xaKhduFkdWLOGihw5+1FAL1jOV5JODz1/bI5V7tqAGWv8IZ8grSb1qOjiJmLopLVjMqhV2hdoABSXh63IINr7U4eSPSFBvy0Fp6ZaOV/hhycNySPqqgPl6SuAspJJGq6+WW4Kdw304FQh6Y6U6uQawwGqXJPCHO7YSCceNromQPkLeIRAec2a9XHodcpZqtwL2aUeJsr7loRmGgWzIyIM+vkmdBcEXF9wUhfRrK/GSCJokxpb2/hsjBC/2tj6GSqymZXkwkxocXpO3Hwsl9et4Nd+iIxr31M7Zb9H5jz9n1bV85E=
after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://strebo.net/html/"