language: php
jdk: openjdk7
sudo: false
php:
- 5.6
- 7.0
- hhvm
before_install:
- composer self-update
- composer update
install:
- travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.zip
- unzip -qq sonar-scanner-2.6.zip
- composer install --prefer-dist
before_script:
- echo "sonar.host.url=http://sonarqube.it.dh-karlsruhe.de" >> sonar-scanner-2.6/conf/sonar-scanner.properties
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist Strebo/ tests/
- sonar-scanner-2.6/bin/sonar-scanner
after_script:
- vendor/bin/test-reporter
after_success:
    curl http://strebo.net/$secret_dir/pull.php > /dev/null
after_failure:
  - ./.send_ticket.sh